# Generated by Django 3.0.6 on 2020-11-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='users/newindex.png', null=True, upload_to='users'),
        ),
    ]
